# pylint: disable=C0103
# Generated by Django 2.0.2 on 2018-02-20 14:17

import django.db.models.deletion
from django.db import migrations, models

import taggit_selectize.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=250)),
                ('is_favorite', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('album',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='tracks',
                     to='album.Album')),
                ('tags',
                 taggit_selectize.managers.TaggableManager(
                     blank=True,
                     help_text='A comma-separated list of tags.',
                     through='taggit.TaggedItem',
                     to='taggit.Tag',
                     verbose_name='Tags')),
            ],
            options={
                'ordering': ('album', 'title'),
            },
        ),
    ]
