# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.6
env:
  global:
    - NODE_ENV=development
install:
  - pip install -r requirements/dev.txt
before_script:
  - node node_modules/webpack/bin/webpack.js
  - cd src
  - python manage.py collectstatic
script:
  - python manage.py lint
  - python manage.py test
