# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.6
before_install: npm install
install:
  - pip install -r requirements/dev.txt
  - node node_modules/webpack/bin/webpack.js
before_script:
  - cd src
script:
  - python manage.py lint
  - python manage.py test
