# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.6
env:
  - SECRET_KEY=dumb_secret_key_for_travis
before_install: npm install
install:
  - pip install -r requirements/dev.txt
  - npm run dev
before_script:
  - cd src
script:
  - python manage.py lint
  - coverage run --source=. manage.py test
after_script:
  - coveralls
