# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.6
install:
  - pip install -r requirements/dev.txt
  - npm install
before_script: node node_modules/webpack/bin/webpack.js
script:
  - python src/manage.py lint
  - python src/manage.py test
