# pylint: disable=C0103
# Generated by Django 2.0.2 on 2018-02-20 14:17

from django.db import migrations, models

import taggit_selectize.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=100)),
                ('album_logo',
                 models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('tags',
                 taggit_selectize.managers.TaggableManager(
                     blank=True,
                     help_text='A comma-separated list of tags.',
                     through='taggit.TaggedItem',
                     to='taggit.Tag',
                     verbose_name='Tags')),
            ],
            options={
                'ordering': ('artist', 'title'),
            },
        ),
    ]
