# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 21:34
from __future__ import unicode_literals

from django.db import migrations
import taggit_selectize.managers


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20170810_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='tags',
            field=taggit_selectize.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='taggit.TaggedItem',
                to='taggit.Tag',
                verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=taggit_selectize.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='taggit.TaggedItem',
                to='taggit.Tag',
                verbose_name='Tags'),
        ),
    ]
