# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20170812_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default=None, max_length=250, blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(default=None, max_length=250, blank=True, null=True),
            preserve_default=False,
        ),
    ]
