# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20170822_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('artist', 'title')},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('album', 'title')},
        ),
    ]
