# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 17:49
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify


def populate_slug(apps, schema_editor):
    album_class = apps.get_model('music', 'Album')
    for album in album_class.objects.all():
        album.slug = '-'.join((slugify(album.artist, allow_unicode=True), slugify(album.title, allow_unicode=True)))
        album.save()

    song_class = apps.get_model('music', 'Song')
    for song in song_class.objects.all():
        song.slug = '-'.join((slugify(song.album.title, allow_unicode=True), slugify(song.title, allow_unicode=True)))
        song.save()


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20170822_2049'),
    ]

    operations = [migrations.RunPython(populate_slug)]
