# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-29 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit_selectize.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('music', '0010_auto_20170822_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=250)),
                ('is_favorite', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('album',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.Album')),
                ('tags',
                 taggit_selectize.managers.TaggableManager(
                     blank=True,
                     help_text='A comma-separated list of tags.',
                     through='taggit.TaggedItem',
                     to='taggit.Tag',
                     verbose_name='Tags')),
            ],
            options={
                'ordering': ('album', 'title'),
            },
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='tags',
        ),
        migrations.DeleteModel(name='Song', ),
    ]
